Buildizer centos test fix

diff --git a/Buildizer b/Buildizer
--- a/Buildizer
+++ b/Buildizer
@@ -31,18 +31,6 @@ ubuntu:
                 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
   - apt-get update
   - apt-get install -y docker-engine=$DOCKER_VERSION
-  test:
-  - (docker daemon > /dev/null 2>&1 &) && COUNTER=0 &&
-       (while ! [ -f /var/run/docker.pid ] ; do
-          if [ $COUNTER -ge 20 ] ; then
-            echo "Unable to start docker daemon" 1>&2 ;
-            exit 1 ;
-          fi ;
-          sleep 1 ;
-          let COUNTER=COUNTER+1 ;
-        done)
-  - (/usr/sbin/sshd > /dev/null 2>&1 &)
-  - bats test/*.spec
 
 centos:
   prepare:
@@ -51,6 +39,8 @@ centos:
     /lib64/security/pam_docker.so: build/pam_docker.so
   before_test:
   - echo "session     required      pam_docker.so" >> /etc/pam.d/system-auth
+  - cat /etc/pam.d/login > /etc/pam.d/sudo
+  - cat /etc/pam.d/login > /etc/pam.d/sshd
   - echo -e "[dockerrepo]\nname=Docker Repository\nbaseurl=https://yum.dockerproject.org/repo/main/centos/\$releasever/\nenabled=1\ngpgcheck=1\ngpgkey=https://yum.dockerproject.org/gpg" > /etc/yum.repos.d/docker.repo
   - yum install -y sudo openssh-server openssh-clients docker-engine-$DOCKER_VERSION
   - curl -o /tmp/epel.rpm https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && rpm -ivh /tmp/epel.rpm
@@ -66,6 +56,18 @@ centos:
     (mountpoint -q $CGROUP || mount -n -t tmpfs -o uid=0,gid=0,mode=0755 cgroup $CGROUP) &&
     (mountpoint -q $SECURITYFS || mount -t securityfs none $SECURITYFS)
   - rm -rf /var/lib/docker/*
+  test:
+  - (docker daemon > /dev/null 2>&1 &) && COUNTER=0 &&
+       (while ! [ -f /var/run/docker.pid ] ; do
+          if [ $COUNTER -ge 20 ] ; then
+            echo "Unable to start docker daemon" 1>&2 ;
+            exit 1 ;
+          fi ;
+          sleep 1 ;
+          let COUNTER=COUNTER+1 ;
+        done)
+  - (/usr/sbin/sshd > /dev/null 2>&1 &)
+  - bats test/*.spec
 
 test_env:
   DOCKER_VERSION: ["1.9.*", "1.10.*", "1.11.*"]
